version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEPTH"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
everycomp = true
tide = true
farmersdelight = true
blahaj = true
sawmill = true
bedrockify = true
creeperoverhaul = true
wilderwild = true
friendsandfoes = true
vanillabackport = true
snowrealmagic = true
biomeswevegone = true
snuffles = true
biomesoplenty = true
easyanvils = true
doubleslabs = true
sereneseasons = true
treechop = true
minecraft = true
