# Use Cloth Config mod for the descriptions.
---
modules:
  enchantment: false
fallDamageReduction: 0.6
fallDamageThreshold: 12
speedReductionHorizontal: 1.0
speedReductionVertical: 1.0
modifyPathFinding: true
playerOnly: false
alwaysNotViewBlocking: true
alwaysLeafWalking: true
sounds:
  volume: 1.0
  playerOnly: true
